# Copyright (c) 2022-2026, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Put image transfer on a task camera, so observations of its ``rgb`` output are generated images."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal

from isaaclab.sensors import CameraCfg
from isaaclab.utils import replace
from isaaclab.utils.modifiers import ModifierCfg

from .cfg import ImageTransferModifierCfg
from .functions import center_crop_resize, depth_to_control, edge_control

CONTROLS = {
    "edge": ("rgb", edge_control),
    "depth": ("distance_to_image_plane", depth_to_control),
}
"""Camera output each control type reads, and the function that prepares it."""


def image_transfer_camera(
    camera: CameraCfg,
    transfer: ImageTransferModifierCfg,
    *,
    control: Literal["edge", "depth"] = "edge",
    control_params: dict | None = None,
    canvas: tuple[int, int] = (832, 480),
    post_modifiers: Sequence[ModifierCfg] = (),
) -> CameraCfg:
    """Return a copy of ``camera`` whose ``rgb`` output is generated by image transfer.

    The copy renders at the model's ``canvas``, prepares controls from the rendered image, generates
    images with ``transfer``, applies ``post_modifiers`` (for example color conversion and PPISP), and
    scales the result back to the camera's original size. Observation terms that read ``rgb`` therefore
    receive generated images of the shape they expect, without changes to the task.

    .. code-block:: python

        env_cfg.scene.base_camera = image_transfer_camera(
            env_cfg.scene.base_camera,
            ImageTransferModifierCfg(backend=WorkerModelCfg(command=[...], prompt="..."), update_frames=4),
            post_modifiers=[ModifierCfg(func=srgb_to_linear), PpispModifierCfg(isp_cfg=isp)],
        )

    Args:
        camera: Camera with an ``rgb`` output, for example a task's policy camera.
        transfer: Image transfer modifier and its model.
        control: Control type: ``"edge"`` (Canny edges of the rendered RGB) or ``"depth"`` (metric depth).
        control_params: Keyword arguments of the control function. Defaults to None, which uses its defaults.
        canvas: Model image size ``(width, height)`` [px]. Defaults to ``(832, 480)``.
        post_modifiers: Modifiers applied to the generated sRGB images before resizing. Each must keep the
            ``(N, H, W, 3)`` image layout and end with uint8. Defaults to none.

    Returns:
        The modified camera configuration.

    Raises:
        ValueError: If the camera has no ``rgb`` output, or the model expects another control type.
    """
    if "rgb" not in camera.data_types:
        raise ValueError(f"The camera must output 'rgb' to carry generated images, got {camera.data_types}.")
    if control not in CONTROLS:
        raise ValueError(f"Unknown control {control!r}; choose one of {sorted(CONTROLS)}.")
    expected = getattr(transfer.backend, "control", None)
    if expected is not None and expected != control:
        raise ValueError(f"The chain prepares {control} controls, but the model expects {expected!r}.")
    renamed = [cfg for cfg in post_modifiers if getattr(cfg, "output", None) not in (None, "rgb")]
    if renamed:
        raise ValueError(f"Post-modifiers must publish 'rgb'; {type(renamed[0]).__name__} sets {renamed[0].output!r}.")
    input_name, prepare = CONTROLS[control]
    modifiers = [
        ModifierCfg(func=prepare, params=dict(control_params or {})),
        replace(transfer, output="rgb"),
        *post_modifiers,
        ModifierCfg(func=center_crop_resize, params={"width": camera.width, "height": camera.height}),
    ]
    width, height = canvas
    return replace(camera, width=width, height=height, data_types=["rgb"], modifiers={input_name: modifiers})
